#!/bin/bash

VERSION=2
if [ "$GET_VERSION" = "1" ]; then
  echo $VERSION
  exit 0
fi

sudo.sh emerge --ask --quiet-build=y --color=y "$@" | tee >(if waitforstring.py "Would you like to"; then gen.sh q i "User Interaction Needed!" >> /dev/null; fi; cat >> /dev/null);
